# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='email',
            name='version',
            field=models.CharField(blank=True, default='V1', max_length=2),
        ),
    ]
