language: python
python:
  - "3.5.1"
env:
  - SECRET_KEY='u@nup3l^ofar)mja-h6khvar^%))*$9^j%9q-9hg0#(3xyel=k' DJANGO_CONFIGURATION='Test' DJANGO=1.9 DJANGO_VERSION_MIN=1.9 DJANGO_VERSION_MAX=1.9
install:
  - pip install -r requirements/test.txt
script:
  - coverage run --source='./' --omit=*/migrations/*,*test* manage.py test
after_success:
  - coveralls
addons:
    code_climate:
        repo_token: 6436422bcd94d4b3f85e7bbefd5aa3938f6226e98d8c443c5a1c059bc37e55d1