language: python
python:
  - "3.5.1"
env:
  - DJANGO_CONFIGURATION='Test'
# command to install dependencies
install: "pip install -r requirements/test.txt"
# command to run tests
script: "python manage.py test"
