language: python
python:
  - "3.5.1"
env:
  - FLEXI_RUN_ENV='test'
# command to install dependencies
install: "pip install -r requirements/common.txt"
# command to run tests
script: "python manage.py test"
