# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0004_auto_20160222_1823'),
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='user',
        ),
        migrations.AddField(
            model_name='seed',
            name='email_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seed', to='emails.Email'),
        ),
        migrations.AddField(
            model_name='seed',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
