# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_login',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip_password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
