# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_auto_20160210_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_type',
            field=models.CharField(blank=True, default='Manual', max_length=40),
        ),
    ]
