# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proxies', '0003_auto_20160210_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='user',
        ),
        migrations.AddField(
            model_name='proxy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='ip_list',
        ),
        migrations.AddField(
            model_name='proxy',
            name='ip_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='proxies.IP'),
        ),
    ]
