# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160210_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.CharField(blank=True, default='https://secure.gravatar.com/avatar/4e8b2b0507e88242ae3786c6cb947490.jpg?s=215&r=g&d=identicon', max_length=256),
        ),
    ]
