# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160210_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.CharField(blank=True, default='https://secure.gravatar.com/avatar/4e8b2b0507e88242ae3786c6cb947490.jpg?d=identicon&r=g&s=215', max_length=256),
        ),
    ]
