# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isp',
            name='members',
        ),
        migrations.AddField(
            model_name='isp',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isp', to=settings.AUTH_USER_MODEL),
        ),
    ]
