# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=200)),
                ('actions', models.CharField(default='RS', max_length=30)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('RN', 'Running'), ('Ps', 'Paused'), ('END', 'Finished')], default='PND', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed_list', models.ManyToManyField(related_name='jobs', to='seed.Seed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
