# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='actions',
            field=models.CharField(default='RS', max_length=200),
        ),
    ]
