# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0002_auto_20160222_1823'),
        ('job', '0002_auto_20160209_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='keywords',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='job',
            name='seed_list',
        ),
        migrations.AddField(
            model_name='job',
            name='seed_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='seed.Seed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('RUN', 'Running'), ('PSD', 'Paused'), ('END', 'Finished')], default='PND', max_length=3),
        ),
    ]
